services:
  sh-reviews:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./src/db:/app/src/db
      - ./src/public/uploads:/app/src/public/uploads
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: sh-reviews
